// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpvlpcshxyvopnttyrnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwdmxwY3NoeHl2b3BudHR5cm5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NDg2OTIsImV4cCI6MjA1OTAyNDY5Mn0.lvLGV0_nEjUfIq_Sh-DqiFlDIPslr2n_YiWNK6D68ZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);